GPU/urls.py
from django.conf import settings
from django.conf.urls.static import static
import accounts
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls", namespace='accounts')),
#     path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path("register/", views.Sign_Up, name="register"),
    path("login/", views.Log_In, name="login"),
    path("logout/", views.Log_Out, name="logout"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    phone_number = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "phone_number", "first_name", "last_name", "password1", "password2")

    def save(self,commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.phone_number = self.cleaned_data["phone_number"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import RegistrationForm

# Create your views here.
def Sign_Up(request):
    if (request.method == 'POST'):
        form = RegistrationForm(request.POST)
        if (form.is_valid()):
            user = form.save()
            login(request, user)
            return redirect('main:home')
    else:
        form = RegistrationForm()
    return render(request, 'accounts/register.html', { 'form': form })

def Log_In(request):
    if (request.method == 'POST'):
        form = AuthenticationForm(data=request.POST)
        if (form.is_valid()):
            user = form.get_user()
            login(request, user)
            return redirect('main:home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def Log_Out(request):
    if (request.method == 'POST'):
            logout(request)
            return redirect('/')

accounts/templates/accounts/login.html
{% extends 'main/base2.html' %}

{% block title %}Login{% endblock  %}

{% load crispy_forms_tags %}

{% block content %}
    <h3> LOGIN </h3>
    <form method="POST" class="form-group" >
        {% csrf_token %}
        {{form|crispy}}
        <p> Don't have an account? Create one <a href="{% url 'accounts:register' %}">here</a></p>
        <button type="Submit" class="btn btn-success">Log in </button>
    </form>

{% endblock  %}

accounts/templates/accounts/register.html
{% extends 'main/base2.html' %}

{% block title %}Sign up {% endblock  %}

{% load crispy_forms_tags%}

{% block content %}
    <h3> REGISTER </h3>
    <p>Already a member?<a href="{% url 'accounts:login' %}"> Login</a></p>
    <form method="POST" class="form-group" >
        {% csrf_token %}
        {{form|crispy}}
        <button type="Submit" class="btn btn-success">Sign up</button>
    </form>
{% endblock  %}