GPU/urls.py
from django.conf import settings
from django.conf.urls.static import static
import accounts
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls", namespace='accounts')),
#     path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path("register/", views.Sign_Up, name="register"),
    path("login/", views.Log_In, name="login"),
    path("logout/", views.Log_Out, name="logout"),
]

main/urls.py
# from django.urls import path
# from main import views

# urlpatterns = [
#     path("home/", views.home, name="home"),
# ]
from django.urls import path
from . import views
from .views import (
    MenuListView,
    menuDetail,
    add_to_cart,
    get_cart_items,
    order_item,
    CartDeleteView,
    order_details,
    admin_view,
    item_list,
    pending_orders,
    ItemCreateView,
    ItemUpdateView,
    ItemDeleteView,
    update_status,
    add_reviews,
)

app_name = "main"

urlpatterns = [
    path('', MenuListView.as_view(), name='home'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin_view/', views.admin_view, name='admin_view'),
    path('pending_orders/', views.pending_orders, name='pending_orders'),
    path('item/new/', ItemCreateView.as_view(), name='item-create'),
    path('update_status/<int:pk>', views.update_status, name='update_status'),
    path('product/<slug>', views.menuDetail, name='product'),
    path('item_list/', views.item_list, name='item_list'),
    path('postReview', views.add_reviews, name='add_reviews'),
    path('item-update/<slug>/', ItemUpdateView.as_view(), name='item-update'),
    path('item-delete/<slug>/', ItemDeleteView.as_view(), name='item-delete'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.get_cart_items, name='cart'),
    path('remove-from-cart/<int:pk>/', CartDeleteView.as_view(), name='remove-from-cart'),
    path('ordered/', views.order_item, name='ordered'),
    path('order_details/', views.order_details, name='order_details'),
    path('order_history/', views.order_history, name='order_history'),      
]

main/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class Item(models.Model):
    LABELS = (
        ('BestSeller', 'BestSeller'),
        ('New', 'New'),
        ('Our pick', 'Our pick'),
    )   

    LABEL_COLOUR = (
        ('danger', 'danger'),
        ('success', 'success'),
        ('primary', 'primary'),
    )
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=250,blank=True)
    price = models.FloatField()
    pieces = models.IntegerField(default=1)
    image = models.ImageField(default='default.png', upload_to='images/')
    labels = models.CharField(max_length=25, choices=LABELS, blank=True)
    label_colour = models.CharField(max_length=15, choices=LABEL_COLOUR, blank=True)
    slug = models.SlugField(default="gpu_name")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("main:product", kwargs={'slug': self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("main:add-to-cart", kwargs={'slug': self.slug})

    def get_item_delete_url(self):
        return reverse("main:Item-delete", kwargs={ 'slug': self.slug})

    def get_update_item_url(self):
        return reverse("main:item-update", kwargs={'slug': self.slug})


class Reviews(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    rslug = models.SlugField()
    review = models.TextField()
    posted_on = models.DateField(default=timezone.now)

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    def __str__(self):
        return self.review

class CartItems(models.Model):
    ORDER_STATUS = (
        ('Active', 'Active'),
        ('Delivered', 'Delivered')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)
    ordered_date = models.DateField(default=timezone.now)
    status = models.CharField(max_length=20, choices=ORDER_STATUS, default='Active')
    delivery_date = models.DateField(default=timezone.now)

    class Meta:
        verbose_name = 'Cart Item'
        verbose_name_plural = 'Cart Items'

    def __str__(self):
        return self.item.title
    
    def get_remove_from_cart_url(self):
        return reverse("main:remove-from-cart", kwargs={
            'pk' : self.pk
        })

    def get_update_status_url(self):
        return reverse("main:update_status", kwargs={
            'pk' : self.pk
        })

main/views.py
from django.shortcuts import render
# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from .models import Item, CartItems, Reviews
from django.contrib import messages
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .decorators import *
from django.db.models import Sum

class MenuListView(ListView):
    model = Item
    template_name = 'main/home.html'
    context_object_name = 'menu_items'

def menuDetail(request, slug):
    item = Item.objects.filter(slug=slug).first()
    reviews = Reviews.objects.filter(rslug=slug)
    context = {
        'item' : item,
        'reviews' : reviews,
    }
    return render(request, 'main/product.html', context)

@login_required
def add_reviews(request):
    if request.method == "POST":
        user = request.user
        rslug = request.POST.get("rslug")
        item = Item.objects.get(slug=rslug)
        review = request.POST.get("review")

        reviews = Reviews(user=user, item=item, review=review, rslug=rslug)
        reviews.save()
        messages.success(request, "Thankyou for reviewing this product!!")
    return redirect(f"/product/{item.slug}")

class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    fields = ['title', 'image', 'description', 'price', 'pieces', 'labels', 'label_colour', 'slug']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

class ItemUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Item
    fields = ['title', 'image', 'description', 'price', 'pieces', 'labels', 'label_colour', 'slug']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        item = self.get_object()
        if self.request.user == item.created_by:
            return True
        return False

class ItemDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Item
    success_url = '/item_list'

    def test_func(self):
        item = self.get_object()
        if self.request.user == item.created_by:
            return True
        return False

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    cart_item = CartItems.objects.create(
        item=item,
        user=request.user,
        ordered=False,
    )
    messages.info(request, "Added to cart Successfully!!!")
    return redirect("main:cart")

@login_required
def get_cart_items(request):
    cart_items = CartItems.objects.filter(user=request.user,ordered=False)
    bill = cart_items.aggregate(Sum('item__price'))
    number = cart_items.aggregate(Sum('quantity'))
    pieces = cart_items.aggregate(Sum('item__pieces'))
    total = bill.get("item__price__sum")
    count = number.get("quantity__sum")
    total_pieces = pieces.get("item__pieces__sum")
    context = {
        'cart_items':cart_items,
        'total': total,
        'count': count,
        'total_pieces': total_pieces
    }
    return render(request, 'main/cart.html', context)

class CartDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = CartItems
    success_url = '/cart'

    def test_func(self):
        cart = self.get_object()
        if self.request.user == cart.user:
            return True
        return False

@login_required
def order_item(request):
    cart_items = CartItems.objects.filter(user=request.user,ordered=False)
    ordered_date=timezone.now()
    cart_items.update(ordered=True,ordered_date=ordered_date)
    messages.info(request, "Item Ordered")
    return redirect("main:order_details")

# @login_required
# def order_history(request):
#     cart_items = CartItems.objects.filter(user=request.user,ordered=False)
#     ordered_date=timezone.now()
#     cart_items.update(ordered=True,ordered_date=ordered_date)
#     messages.info(request, "Item Ordered")
#     return redirect("main:order_history")

@login_required
def order_details(request):
    items = CartItems.objects.filter(user=request.user, ordered=True,status="Active").order_by('-ordered_date')
    cart_items = CartItems.objects.filter(user=request.user, ordered=True,status="Delivered").order_by('-ordered_date')
    bill = items.aggregate(Sum('item__price'))
    number = items.aggregate(Sum('quantity'))
    pieces = items.aggregate(Sum('item__pieces'))
    total = bill.get("item__price__sum")
    count = number.get("quantity__sum")
    total_pieces = pieces.get("item__pieces__sum")
    context = {
        'items':items,
        'cart_items':cart_items,
        'total': total,
        'count': count,
        'total_pieces': total_pieces
    }
    return render(request, 'main/order_details.html', context)

@login_required
def order_history(request):
    items = CartItems.objects.filter(user=request.user, ordered=True,status="Active").order_by('-ordered_date')
    cart_items = CartItems.objects.filter(user=request.user, ordered=True,status="Delivered").order_by('-ordered_date')
    bill = items.aggregate(Sum('item__price'))
    number = items.aggregate(Sum('quantity'))
    pieces = items.aggregate(Sum('item__pieces'))
    total = bill.get("item__price__sum")
    count = number.get("quantity__sum")
    total_pieces = pieces.get("item__pieces__sum")
    context = {
        'items':items,
        'cart_items':cart_items,
        'total': total,
        'count': count,
        'total_pieces': total_pieces
    }
    return render(request, 'main/order_history.html', context)

@login_required(login_url='/accounts/login/')
@admin_required
def admin_view(request):
    cart_items = CartItems.objects.filter( ordered=True,status="Delivered").order_by('-ordered_date')
    context = {
        'cart_items':cart_items,
    }
    return render(request, 'main/admin_view.html', context)

@login_required(login_url='/accounts/login/')
@admin_required
def item_list(request):
    items = Item.objects.filter(created_by=request.user)
    context = {
        'items':items
    }
    return render(request, 'main/item_list.html', context)

@login_required
@admin_required
def update_status(request,pk):
    if request.method == 'POST':
        status = request.POST['status']
    cart_items = CartItems.objects.filter( ordered=True,status="Active",pk=pk)
    delivery_date=timezone.now()
    if status == 'Delivered':
        cart_items.update(status=status, delivery_date=delivery_date)
    return render(request, 'main/pending_orders.html')

@login_required(login_url='/accounts/login/')
@admin_required
def pending_orders(request):
    items = CartItems.objects.filter( ordered=True,status="Active").order_by('-ordered_date')
    context = {
        'items':items,
    }
    return render(request, 'main/pending_orders.html', context)

@login_required(login_url='/accounts/login/')
@admin_required
def admin_dashboard(request):
    cart_items = CartItems.objects.filter(item__created_by=request.user, ordered=True)
    pending_total = CartItems.objects.filter(item__created_by=request.user, ordered=True,status="Active").count()
    completed_total = CartItems.objects.filter(item__created_by=request.user, ordered=True,status="Delivered").count()
    total = CartItems.objects.filter(item__created_by=request.user, ordered=True).aggregate(Sum('item__price'))
    income = total.get("item__price__sum")
    context = {
        'pending_total' : pending_total,
        'completed_total' : completed_total,
        'income' : income,
    }
    return render(request, 'main/admin_dashboard.html', context)

main/templates/main/admin_dashboard.html
{<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Admin Dashboard</title>
  <style type="text/css">
    .sidenav {
      height: 100%;
      width: 180px;
      position: fixed;
      z-index:1;
      top:0;
      left:0;
      background-color:#111;
      overflow-x:hidden;
      padding-top: 20px;
      box-shadow: 0px 5px 10px #000000
    }

    .sidenav a {
      padding: 6px 8px 6px 16px;
      text-decoration: none;
      color: #818181;
      display: block;
      font-size: 20px;
      margin-left: 10px
    }

    .sidenav a:hover {
      color:#f5f2d0;
    }

    .main {
      margin-left:15%;
      margin-right:80%
      padding:0px 10px;
      font-family: 'Ubuntu', sans-serif;
    }
    .product .main .container .row img{
      max-width: 540px;
      max-height: 450px;
      width: fit-content;
    }

    .product .main .container .row .content{
      display: flex;
      flex-direction: column;
      text-align: center;
      justify-content: center;
    }

    .product .main .container .row .information{
      display: flex;
      flex-direction: column;
      text-align: center;
      justify-content: center;
    }
  </style>

  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"></script>
  </head>
  <body>
    <div id="wrapper" style="font-family: 'Ubuntu', sans-serif;">
      <div class="sidenav">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
          <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'main:admin_dashboard' %}">
            <div class="sidebar-brand-text mx-3" href="/" ><img src="../media/logo/logo.png" height="75px"></div>
          </a>
          <hr class="sidebar-divider">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:admin_dashboard' %}">
              <i class="fa fa-bandcamp"></i>
              <span style="font-size:12px; letter-spacing: 4px">ADMIN INTERFACE</span></a>
          </li>
          <hr class="sidebar-divider">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:item-create' %}">
              <i class="fa fa-plus"></i>
              <span>Add Products</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:item_list' %}">
              <i class="fa fa-plus"></i>
              <span>View Items</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:admin_view' %}">
              <i class="fa fa-check"></i>
              <span>Completed Orders</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:pending_orders' %}">
              <i class="fa fa-bell"></i>
              <span>Pending Orders</span>
            </a>
          </li>
          <hr class="sidebar-divider">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:home' %}">
              <i class="fa fa-home"></i>
              <span>Home</span></a>
          </li>
          <li class="sidebar">
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm" style="margin-left:10px; margin-top:50px">Logout</button>
            </form>
          </li>
        </div>
          <div id="content", name="content", class="main">
            <div class="col-8" style="text-align: centre">
              <h1 class="mt-2"> DASHBOARD </h1>
              <hr class="sidebar-divider d-none d-md-block">
            </div>
          
            <div id="content-wrapper" class="d-flex flex-column">
              <div id="content">
                 
                <div class="container-fluid">
                  <div class="row">
                    <div class="col-xl-4 col-md-4 mb-4">
                      <div class="card border-left-success shadow h-100 py-2">
                        <div class="card-body">
                          <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                              <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Total Earnings</div>
                              <div class="h5 mb-0 font-weight-bold text-gray-800">₹ {{ income }}</div>
                            </div>
                            <div class="col-auto">
                              <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-4 col-md-4 mb-4">
                      <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                          <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Delivered</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ completed_total }}</div>
                          </div>
                          <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-xl-4 col-md-4 mb-4">
                    <div class="card border-left-danger shadow h-100 py-2">
                      <div class="card-body">
                        <div class="row no-gutters align-items-center">
                          <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Pending Orders</div>
                              <div class="h5 mb-0 font-weight-bold text-gray-800">{{ pending_total }}</div>
                          </div>
                          <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                          </div>
                        </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/cart.html
{% extends "main/base.html" %}
{% block content %}
<div class="cart">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 mt-5">
                <h3 class="text-center">YOUR CART</h3>
                {% if cart_items %}
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Price</th>
                            <th scope="col">Total Pieces</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for cart in cart_items %}
                        <tr>
                            <td>{{ cart.item.title }} <span class="badge badge-{{ cart.item.label_colour }}">{{ cart.item.labels }}</span></td>
                            <td>{{ cart.item.description }}</td>
                            <td>{{ cart.item.price }}</td>
                            <td>{{ cart.item.pieces }} pieces</td>
                            <td><a class="btn btn-danger" href="{% url 'main:remove-from-cart' cart.id %}">Delete</a></td>
                        </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h4 class="text-center">Your cart is empty. Please add items first!</h4>
                {% endif %}
            </div>
            <div class="col-sm-3 mt-5 ">
                <div class="content-section">
                    <h3 class="text-center">ORDER SUMMARY</h3>
                    <ul class="list-group list-group-flush">
                    <li class="list-group-item text-dark">Total: {{ total }}</li>
                    <li class="list-group-item text-dark">Number of Boxes: {{ count }}</li>
                    <li class="list-group-item text-dark">Total Pieces: {{ total_pieces }}</li>
                    </ul>
                    <a class="btn btn-primary text-WHITE" style="margin:15px" href="{% url 'main:ordered' %}">Proceed To Checkout</a>
                      
                </div>
            </div>
        </div>
    </div>
    <div><a class="btn btn-primary text-WHITE" style="margin:10px; position:absolute; right:0; bottom:0; width:176px;" href="/">Continue Buying</a></div>
</div>
{% endblock content %}

main/templates/main/item_confirm_delete.html
{% extends "main/base.html" %}
{% block content %}
    <div class="content-section container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Item</legend>
                <h2>Are you sure you want to delete the post "{{ item.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'main:item_list' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/layout2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Admin Dashboard</title>
  <style type="text/css">
    .sidenav {
      height: 100%;
      width: 180px;
      position: fixed;
      z-index:1;
      top:0;
      left:0;
      background-color:#111;
      overflow-x:hidden;
      padding-top: 20px;
      box-shadow: 0px 5px 10px #000000
    }

    .sidenav a {
      padding: 6px 8px 6px 16px;
      text-decoration: none;
      color: #818181;
      display: block;
      font-size: 20px;
      margin-left: 10px
    }

    .sidenav a:hover {
      color:#f5f2d0;
    }

    .main {
      margin-left:15%;
      margin-right:80%
      padding:0px 10px;
      font-family: 'Ubuntu', sans-serif;
    }
    .product .main .container .row img{
      max-width: 540px;
      max-height: 450px;
      width: fit-content;
    }

    .product .main .container .row .content{
      display: flex;
      flex-direction: column;
      text-align: center;
      justify-content: center;
    }

    .product .main .container .row .information{
      display: flex;
      flex-direction: column;
      text-align: center;
      justify-content: center;
    }
  </style>

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js"></script>
</head>

<body>
    <div id="wrapper">
      <div class="sidenav">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
          <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'main:admin_dashboard' %}">
            <div class="sidebar-brand-text mx-3" href="/" ><img src="../media/logo/logo.png" height="75px"></div>
          </a>
          <hr class="sidebar-divider">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:admin_dashboard' %}">
              <i class="fa fa-bandcamp"></i>
              <span style="font-size:12px; letter-spacing: 4px">ADMIN INTERFACE</span></a>
          </li>
          <hr class="sidebar-divider">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:item-create' %}">
              <i class="fa fa-plus"></i>
              <span>Add Products</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:item_list' %}">
              <i class="fa fa-plus"></i>
              <span>View Items</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:admin_view' %}">
              <i class="fa fa-check"></i>
              <span>Completed Orders</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:pending_orders' %}">
              <i class="fa fa-bell"></i>
              <span>Pending Orders</span>
            </a>
          </li>
          <hr class="sidebar-divider">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:home' %}">
              <i class="fa fa-home"></i>
              <span>Home</span></a>
          </li>
          <li class="sidebar">
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm" style="margin-left:10px; margin-top:50px">Logout</button>
            </form>
          </li>
        </div>
        <div id="content", name="content", class="main">
            <div class="col-8" style="text-align: centre">
              <h1 class="mt-2"> ADMIN INTERFACE </h1>
              <hr class="sidebar-divider d-none d-md-block">
            </div>
            
        </ul>
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
              <div class="container-fluid" style="font-family: 'Ubuntu', sans-serif;">
                  {% block content %}{% endblock %}
              </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>